config/routes.rb
Pcbl::Application.routes.draw do
  devise_for :users
  root :to => 'welcome#index'
  resources :court_cases

  root :to => 'welcome#index'

end

app/models/court_case.rb
class CourtCase < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	layout :layout_by_resource

	protected
		def after_sign_in_path_for(resource)
			flash[:notice] = "You have successfully signed in."
			stored_location_for(resource) || root_path
		end

		def after_sign_out_path_for(resource)
			flash[:notice] = "You have signed out"
			root_path
		end

		def layout_by_resource
			if devise_controller?
				'login'
			else
				'application'
			end
		end
end

app/controllers/court_cases_controller.rb
class CourtCasesController < ApplicationController
  # GET /court_cases
  # GET /court_cases.json
  def index
    @court_cases = CourtCase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @court_cases }
    end
  end

  # GET /court_cases/1
  # GET /court_cases/1.json
  def show
    @court_case = CourtCase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @court_case }
    end
  end

  # GET /court_cases/new
  # GET /court_cases/new.json
  def new
    @court_case = CourtCase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @court_case }
    end
  end

  # GET /court_cases/1/edit
  def edit
    @court_case = CourtCase.find(params[:id])
  end

  # POST /court_cases
  # POST /court_cases.json
  def create
    @court_case = CourtCase.new(params[:court_case])

    respond_to do |format|
      if @court_case.save
        format.html { redirect_to @court_case, notice: 'Court case was successfully created.' }
        format.json { render json: @court_case, status: :created, location: @court_case }
      else
        format.html { render action: "new" }
        format.json { render json: @court_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /court_cases/1
  # PUT /court_cases/1.json
  def update
    @court_case = CourtCase.find(params[:id])

    respond_to do |format|
      if @court_case.update_attributes(params[:court_case])
        format.html { redirect_to @court_case, notice: 'Court case was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @court_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /court_cases/1
  # DELETE /court_cases/1.json
  def destroy
    @court_case = CourtCase.find(params[:id])
    @court_case.destroy

    respond_to do |format|
      format.html { redirect_to court_cases_url }
      format.json { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController	
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/court_cases_helper.rb
module CourtCasesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/court_cases/_form.html.erb
<%= form_for(@court_case) do |f| %>
  <% if @court_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@court_case.errors.count, "error") %> prohibited this court_case from being saved:</h2>

      <ul>
      <% @court_case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :case_no %><br />
    <%= f.text_field :case_no %>
  </div>
  <div class="field">
    <%= f.label :case_title %><br />
    <%= f.text_field :case_title %>
  </div>
  <div class="field">
    <%= f.label :legal_counsel %><br />
    <%= f.text_field :legal_counsel %>
  </div>
  <div class="field">
    <%= f.label :court %><br />
    <%= f.number_field :court %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :case_status %><br />
    <%= f.number_field :case_status %>
  </div>
  <div class="field">
    <%= f.label :is_approved %><br />
    <%= f.check_box :is_approved %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :is_deleted %><br />
    <%= f.check_box :is_deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/court_cases/edit.html.erb
<h1>Editing court_case</h1>

<%= render 'form' %>

<%= link_to 'Show', @court_case %> |
<%= link_to 'Back', court_cases_path %>

app/views/court_cases/index.html.erb
<h1>Listing court_cases</h1>

<table>
  <tr>
    <th>Case no</th>
    <th>Case title</th>
    <th>Legal counsel</th>
    <th>Court</th>
    <th>Description</th>
    <th>Case status</th>
    <th>Is approved</th>
    <th>User</th>
    <th>Is deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @court_cases.each do |court_case| %>
  <tr>
    <td><%= court_case.case_no %></td>
    <td><%= court_case.case_title %></td>
    <td><%= court_case.legal_counsel %></td>
    <td><%= court_case.court %></td>
    <td><%= court_case.description %></td>
    <td><%= court_case.case_status %></td>
    <td><%= court_case.is_approved %></td>
    <td><%= court_case.user_id %></td>
    <td><%= court_case.is_deleted %></td>
    <td><%= link_to 'Show', court_case %></td>
    <td><%= link_to 'Edit', edit_court_case_path(court_case) %></td>
    <td><%= link_to 'Destroy', court_case, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Court case', new_court_case_path %>

app/views/court_cases/new.html.erb
<h1>New court_case</h1>

<%= render 'form' %>

<%= link_to 'Back', court_cases_path %>

app/views/court_cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Case no:</b>
  <%= @court_case.case_no %>
</p>

<p>
  <b>Case title:</b>
  <%= @court_case.case_title %>
</p>

<p>
  <b>Legal counsel:</b>
  <%= @court_case.legal_counsel %>
</p>

<p>
  <b>Court:</b>
  <%= @court_case.court %>
</p>

<p>
  <b>Description:</b>
  <%= @court_case.description %>
</p>

<p>
  <b>Case status:</b>
  <%= @court_case.case_status %>
</p>

<p>
  <b>Is approved:</b>
  <%= @court_case.is_approved %>
</p>

<p>
  <b>User:</b>
  <%= @court_case.user_id %>
</p>

<p>
  <b>Is deleted:</b>
  <%= @court_case.is_deleted %>
</p>


<%= link_to 'Edit', edit_court_case_path(@court_case) %> |
<%= link_to 'Back', court_cases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>PCBL</title>
		<%= csrf_meta_tags %>
		<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
		<link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
		<link href="/assets/pcbl.css" rel="stylesheet" type="text/css" />
	    <link href="/assets/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
	    <link href="/assets/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
	    <link href="/assets/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
	    <link href="/assets/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
	</head>

	<body class="skin-red layout-top-nav">
		<div class="wrapper">
			<header class="top-head" role="banner"></header>
			<header class="main-header">
				<nav class="navbar navbar-static-top">
					<div class="container-fluid">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
								<i class="fa fa-bars"></i>
							</button>
						</div>

						<div class="collapse navbar-collapse" id="navbar-collapse">
							<ul class="nav navbar-nav">
								<li class="active"><a href="/"> Dashboard <span class="sr-only">(current)</span></a></li>
								<li><%= link_to "Approved Cases", court_cases_path %></li>
								<li><%#= link_to "UnApproved Cases", unapproved_cases_path %></li>
								<li><%#= link_to "DisApproved Cases", disapproved_cases_path %></li>
								<% if false %>
									<% if can? :create, CourtCase %><li><%= link_to "New Case", new_court_case_path %></li><% end %>
									<li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
								<% end %>
							</ul>
							<ul class="pull-right nav navbar-nav" style="margin-right:15px;">
								<li class="active"><a href="javascript:void(0);" style="cursor: default;">Username: rai<%#= current_user.username %> login as <%#= current_user.role %>admin</a></li>
							</ul>
						</div>
					</div>
				</nav>
			</header>

			<%= yield %>
			
			<footer class="main-footer">
				<div class="container-fluid">
					<strong>Copyright &copy; PITB</strong> All rights reserved.
				</div>
			</footer>
		</div>

		
		<script src="/assets/plugins/jQuery/jQuery-2.1.4.min.js"></script>
		<%= javascript_include_tag "application" %>
		<script src="/assets/app.min.js" type="text/javascript"></script>
		<script src="/assets/demo.js" type="text/javascript"></script>		
		<script src="/assets/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="/assets/plugins/datatables/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="/assets/plugins/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="/assets/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			$(function () {
				$("#example1").dataTable();
				$('.example2').dataTable({
					"bPaginate": true,
					"bLengthChange": false,
					"bFilter": false,
					"bSort": false,
					"bInfo": true,
					"bAutoWidth": false,
					"scrollX": true
				});
			});

			$(function() {
				$( ".datepicker" ).datepicker({
					format: "dd-mm-yyyy",
					autoclose: true
				});
			});
			$(document).on('nested:fieldAdded', function(event){
				$( ".datepicker" ).datepicker({
					format: "dd-mm-yyyy",
					autoclose: true
				});
			});
		</script>
	</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>PCBL</title>
		<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
		<link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
		<link href="/assets/pcbl.css" rel="stylesheet" type="text/css" />
		<link href="/assets/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
	</head>
	<body class="login-page">
		<div class="login-box">
			<div class="login-box-body">
				<div class="login-logo">
					<a href="login.html"><img src="/assets/logo.png" class="img-responsive" /></a>
				</div><!-- /.login-logo -->

				<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
					<div class="form-group has-feedback">
						<%= f.text_field :username, { class: "form-control", placeholder: "Email", autofocus: true } %>
					</div>
					<div class="form-group has-feedback">
						<%= f.password_field :password, { class: "form-control", placeholder: "Password", autocomplete: "off" } %>
					</div>
					<div class="row">
						<div class="col-xs-4 col-xs-offset-4">
							<%= f.submit "Sign In", { class: "btn btn-primary btn-block btn-flat sign_in_btn" } %>
						</div><!-- /.col -->
					</div>
				<% end %>
			</div><!-- /.login-box-body -->
		</div><!-- /.login-box -->

		<!-- jQuery 2.1.4 -->
		<script src="/assets/plugins/jQuery/jQuery-2.1.4.min.js"></script>
		<!-- Bootstrap 3.3.2 JS -->
		<script src="/assets/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>